sudo: required

language: c

compiler: clang

services:
  - docker

install:
  - sudo pip install codecov
  - docker pull dalealleshouse/algo_test_runner_c:latest

script: ./ci_validate.sh

after_success:
  - codecov -X gcov
